name: QLBase Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v5
        with:
          go-version: '>=1.17.0'

      - name: Go version
        run: go version

      - name: Install Qrepo
        run: sh -c "$(curl -fsSL https://raw.githubusercontent.com/nthnn/Qrepo/master/support/install.sh)"

      - name: Build QLBase
        run: |
          qrepo run deploy

      - name: Upload QLBase build
        uses: actions/upload-artifact@v4
        with:
          name: qlbase
          path: qlbase.zip
